// GENERAL
export const BASE_URL = 'http://quissatrip.pe.hu/app';
export const CATEGORIES = 'CATEGORIES';
export const CATEGORY_LIST = 'CATEGORY_LIST';
export const FETCH_EVENTS = 'FETCH_EVENTS';
export const FETCH_CITY_INFO = 'FETCH_CITY_INFO';

// USER
export const FETCH_USER = 'FETCH_USER';
export const FETCH_USER_ERROR = 'FETCH_USER_ERROR';
export const LOGOUT = 'LOGOUT';

// ENTITIES
export const FETCH_PLACES = 'FETCH_PLACES';
export const FETCH_SINGLE_PLACE = 'FETCH_SINGLE_PLACE';
export const FETCH_PLACES_OF_CIRCUIT = 'FETCH_PLACES_OF_CIRCUIT';

// COMMERCE
export const FETCH_COMMERCE_CATEGORIES = 'FETCH_COMMERCE_CATEGORIES';
export const FETCH_COMMERCE_SINGLE = 'FETCH_COMMERCE_SINGLE';
export const FETCH_COMMERCES = 'FETCH_COMMERCES';

// SEARCH
export const FETCH_SEARCH = 'FETCH_SEARCH';
export const SET_FILTER_TYPE = 'SET_FILTER_TYPE';
export const SET_FILTER_OPEN = 'SET_FILTER_OPEN';
export const SET_FILTER_CLOSE = 'SET_FILTER_CLOSE';
export const SET_FILTER_CATEGORY = 'SET_FILTER_CATEGORY';

// ROLEZINHOS
export const FETCH_ROLEZINHOS = 'FETCH_ROLEZINHOS';
