// GENERAL
export const BASE_URL = 'http://lucascraveiropaes.com/app';
export const CIRCUITS = 'CIRCUITS';

// USER
export const FETCH_USER = 'FETCH_USER';
export const FETCH_USER_ERROR = 'FETCH_USER_ERROR';
export const LOGOUT = 'LOGOUT';

// ENTITIES
export const FETCH_PLACES = 'FETCH_PLACES';
export const FETCH_SINGLE_PLACE = 'FETCH_SINGLE_PLACE';
export const FETCH_PLACES_OF_CIRCUIT = 'FETCH_PLACES_OF_CIRCUIT';

// COMMERCE
export const FETCH_COMMERCE_CATEGORIES = 'FETCH_COMMERCE_CATEGORIES';
export const FETCH_COMMERCE_SINGLE = 'FETCH_COMMERCE_SINGLE';
export const FETCH_COMMERCES = 'FETCH_COMMERCES';

// SEARCH
export const FETCH_SEARCH = 'FETCH_SEARCH';

// ROLEZINHOS
export const FETCH_ROLEZINHOS = 'FETCH_ROLEZINHOS';
