// GENERAL
export const OPEN_APP_COUNTER = 'OPEN_APP_COUNTER';

// USER
export const FETCH_USER = 'FETCH_USER';

// ENTITIES
export const FETCH_PLACES = 'FETCH_PLACES';
export const FETCH_SINGLE_PLACE = 'FETCH_SINGLE_PLACE';
export const FETCH_PLACES_OF_CIRCUIT = 'FETCH_PLACES_OF_CIRCUIT';

// ROLEZINHOS
export const FETCH_ROLEZINHOS = 'FETCH_ROLEZINHOS';
